### ISSUE TITLE
feature request: add a binary to convert emoji from CLI with a simple search and replace

### ISSUE THREAD

**Issue by ccoVeille** [donatj/ghemoji#13]
My request follows this discussion we had with @donatj (more a monolog, haha)

https://github.com/wfxr/emoji-cli/issues/2#issuecomment-2088616693

I would like to have the ability to convert text this way (let's assume the name of the binary would be `emoji-cli`)

```console
$ emoji-cli "Foo bar :smile:"
Foo bar 😀
```

or

```console
$ echo "Foo bar :smile:" | emoji-cli
Foo bar 😀
```

It could be useful for piping the result of `git log`

**Comment by ccoVeille** [comment]
I asked about your opinion about this feature. I can code it.

**Comment by donatj** [comment]
I'd call it `ghemoji` in keeping with the project, but I'm open to a ghemoji command that lives in `cmd/ghemoji`

**Comment by ccoVeille** [comment]
I will then, you can assign me the issue. I will first work on a small refactoring/refreshing of ghupdater, stay tuned

**Comment by donatj** [comment]
This is done and in place.

```
go install github.com/donatj/ghemoji/cmd/ghemoji@latest
```
