### ISSUE TITLE
documentation: explain where the emojis come from

### ISSUE THREAD

**Issue by ccoVeille** [donatj/ghemoji#14]
https://github.com/github/gemoji only contains the Unicode emoji

so this project only uses the Unicode ones.

There are a lot of emojis that GitHub supports and that are not supported by current tool

People might expect to see them.

But these "emojis" supported by GitHub might have no reference, so won't be rendered, unless maybe with fonte awesome (if this leads to something, it would be in another issue)

That's why I think it should be documented

**Comment by ccoVeille** [comment]
I'm talking about emoji like :octocat: :electron: and co

**Comment by donatj** [comment]
> where the emojis come

When two unicode characters love eachother very much… 

The non-unicode emoji are actually considered deprecated and only still work for historical reasos.

https://github.com/github/gemoji/pull/158

This libraries goal is just largely to be a Go version of [github/gemoji](https://github.com/github/gemoji) - and gemoji no longer supports them, so neither do I.
