### ISSUE TITLE
feature request: other sources of emojis

### ISSUE THREAD

**Issue by ccoVeille** [donatj/ghemoji#15]
Here is a page that tracks the GitHub emojis
https://gist.github.com/rxaviers/7360908

There is also an endpoint that could be used directly https://api.github.com/emojis

I'm unsure if they could be rendered via a font containing fontawesome.

To be discussed

**Comment by donatj** [comment]
The emoji here come from the actual source code that drives GitHub.

Anything else is outside the scope of this project.

https://github.com/github/gemoji/blob/master/db/emoji.json
