### ISSUE TITLE
documentation: add explanation on how updating the emojis

### ISSUE THREAD

**Issue by ccoVeille** [donatj/ghemoji#16]
Anything that will mention this will be OK

```
go run cmd/ghupdate/main.go -- emoji.go
```

**Comment by donatj** [comment]
It's a `go generate` step. 

https://github.com/donatj/ghemoji/blob/be086fb19f41bf50240eb4a91144bebe5449f81d/methods.go#L5-L6

You only need to run `go generate ./...`

**Comment by ccoVeille** [comment]
I get it now, I totally missed the go generate hidden in one file

My point remains anyway, it should be documented :smile:

**Comment by donatj** [comment]
I've been keeping this library up to date for 8 years without issue. I'm the only maintainer. I'm not going to forget how to do it.
